# Generated by Django 4.2.8 on 2024-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='UserFriend id')),
                ('uid', models.BigIntegerField(verbose_name='uid')),
                ('friend_uid', models.BigIntegerField(verbose_name='好友uid')),
                ('delete_status', models.IntegerField(choices=[(0, '正常'), (1, '删除')], default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'user_friend',
                'indexes': [models.Index(fields=['uid'], name='user_friend_uid_fcd392_idx'), models.Index(fields=['uid', 'friend_uid'], name='user_friend_uid_379049_idx'), models.Index(fields=['create_time'], name='user_friend_create__399bb8_idx'), models.Index(fields=['update_time'], name='user_friend_update__828fd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='UserApply id')),
                ('uid', models.BigIntegerField(verbose_name='申请人uid')),
                ('type', models.IntegerField(choices=[(1, '加好友')], verbose_name='申请类型')),
                ('target_id', models.BigIntegerField(verbose_name='接收人uid')),
                ('msg', models.CharField(max_length=64, verbose_name='申请信息')),
                ('status', models.IntegerField(choices=[(1, '待审批'), (2, '同意')], verbose_name='申请状态')),
                ('read_status', models.IntegerField(choices=[(1, '未读'), (2, '已读')], verbose_name='阅读状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'user_apply',
                'indexes': [models.Index(fields=['uid', 'target_id'], name='user_apply_uid_b0f14c_idx'), models.Index(fields=['target_id', 'read_status'], name='user_apply_target__ea20f8_idx'), models.Index(fields=['target_id'], name='user_apply_target__ffade9_idx'), models.Index(fields=['create_time'], name='user_apply_create__8ec175_idx'), models.Index(fields=['update_time'], name='user_apply_update__8bc454_idx')],
            },
        ),
    ]
