# Generated by Django 4.2.8 on 2024-01-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userapply',
            name='user_apply_uid_b0f14c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userapply',
            name='user_apply_target__ea20f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userapply',
            name='user_apply_target__ffade9_idx',
        ),
        migrations.RemoveIndex(
            model_name='userfriend',
            name='user_friend_uid_379049_idx',
        ),
        migrations.RenameIndex(
            model_name='userfriend',
            new_name='user_friend_uid_id_011553_idx',
            old_name='user_friend_uid_fcd392_idx',
        ),
        migrations.RemoveField(
            model_name='userapply',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='friend_uid',
        ),
        migrations.AddField(
            model_name='userapply',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applies_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfriend',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL, verbose_name='好友'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies_sent', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='userapply',
            index=models.Index(fields=['uid', 'target'], name='user_apply_uid_id_db87e0_idx'),
        ),
        migrations.AddIndex(
            model_name='userapply',
            index=models.Index(fields=['target', 'read_status'], name='user_apply_target__ea20f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userapply',
            index=models.Index(fields=['target'], name='user_apply_target__ffade9_idx'),
        ),
        migrations.AddIndex(
            model_name='userfriend',
            index=models.Index(fields=['uid', 'friend'], name='user_friend_uid_id_a759f1_idx'),
        ),
    ]
