# Generated by Django 4.2.6 on 2023-10-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=32, unique=True, verbose_name='微信openid用户标识')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='用户昵称')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像')),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], null=True, verbose_name='性别')),
                ('is_active', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=2, verbose_name='在线状态')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后上下线时间')),
                ('ip_info', models.JSONField(null=True, verbose_name='ip信息')),
                ('item_id', models.BigIntegerField(null=True, verbose_name='佩戴的徽章id')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '拉黑')], default=0, verbose_name='使用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
