# Generated by Django 5.0 on 2023-12-16 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.CreateModel(
            name='ItemConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.IntegerField(choices=[(1, '改名卡'), (2, '徽章')], verbose_name='物品类型')),
                ('img', models.URLField(max_length=255, null=True, verbose_name='物品图片')),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='物品描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'item_config',
                'indexes': [models.Index(fields=['create_time'], name='item_create_time'), models.Index(fields=['update_time'], name='item_update_time')],
            },
        ),
        migrations.CreateModel(
            name='UserBackpack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, '待使用'), (1, '已使用')], verbose_name='使用状态')),
                ('idempotent', models.CharField(max_length=64, unique=True, verbose_name='幂等号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.itemconfig')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_backpack',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='backpacks',
            field=models.ManyToManyField(related_name='users', through='users.UserBackpack', to='users.itemconfig', verbose_name='用户与物品的关联'),
        ),
        migrations.AddIndex(
            model_name='userbackpack',
            index=models.Index(fields=['create_time'], name='backpack_create_time'),
        ),
        migrations.AddIndex(
            model_name='userbackpack',
            index=models.Index(fields=['update_time'], name='backpack_update_time'),
        ),
    ]
