# Generated by Django 5.0 on 2023-12-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbackpack',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='userbackpack',
            old_name='user_id',
            new_name='user',
        ),
    ]
