# Generated by Django 5.0 on 2023-12-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_item_id_userbackpack_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbackpack',
            old_name='item',
            new_name='items',
        ),
    ]
