# Generated by Django 5.0 on 2023-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_item_userbackpack_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbackpack',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='userbackpack',
            name='status',
            field=models.IntegerField(choices=[(0, '待使用'), (1, '已使用')], default=0, verbose_name='使用状态'),
        ),
    ]
