# Generated by Django 4.2.8 on 2023-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_backpacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'IP'), (2, 'UID')], verbose_name='拉黑目标类型')),
                ('target', models.CharField(max_length=32, verbose_name='拉黑目标')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
                'unique_together': {('type', 'target')},
            },
        ),
    ]
