# Generated by Django 4.2.9 on 2024-01-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmoji',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expression_url', models.CharField(max_length=255, verbose_name='表情地址')),
                ('delete_status', models.IntegerField(choices=[(0, '正常'), (1, '删除')], default=0, verbose_name='使用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户表情包',
                'verbose_name_plural': '用户表情包',
            },
        ),
    ]
