[tool.poetry]
name = "afanchatserver"
version = "0.1.0"
description = "AfanChat服务端"
authors = ["flz <f2095522823@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django-ninja-extra = "^0.19.3"
django-environ="^0.11.2"
setuptools = "^69.0.2"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
