# Generated by Django 4.2.8 on 2024-01-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_secureinvokerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='敏感词')),
            ],
            options={
                'verbose_name': '敏感词库',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, '正常消息'), (2, '撤回消息'), (3, '图片'), (4, '文件'), (5, '语音'), (6, '视频'), (7, '表情'), (8, '系统消息')], default=1, verbose_name='消息类型 1正常文本 2.撤回消息'),
        ),
        migrations.CreateModel(
            name='MessageMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '点赞'), (2, '举报')], verbose_name='标记类型 1点赞 2举报')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '删除')], verbose_name='消息状态 0正常 1取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_mark_user', to=settings.AUTH_USER_MODEL, verbose_name='标记人')),
            ],
            options={
                'verbose_name': '消息标记表',
                'indexes': [models.Index(fields=['msg'], name='chat_messag_msg_id_804850_idx'), models.Index(fields=['user'], name='chat_messag_user_id_19541c_idx'), models.Index(fields=['create_time'], name='chat_messag_create__f5e142_idx'), models.Index(fields=['update_time'], name='chat_messag_update__4937c9_idx')],
            },
        ),
    ]
