# Generated by Django 4.2.8 on 2024-01-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_sensitiveword_alter_message_type_messagemark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemark',
            name='status',
        ),
    ]
