# Generated by Django 4.2.8 on 2024-01-08 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_messagemark_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemark',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '删除')], default=0, verbose_name='消息状态 0正常 1取消'),
            preserve_default=False,
        ),
    ]
