# Generated by Django 4.2.8 on 2024-01-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messagemark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='messagemark',
            name='status',
            field=models.IntegerField(choices=[(1, '确认'), (2, '取消')], verbose_name='动作类型 1确认 2取消'),
        ),
    ]
