# Generated by Django 4.2.9 on 2024-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_content_alter_messagemark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.IntegerField(choices=[(1, '群主'), (2, '管理员'), (3, '普通成员'), (4, '被移除的成员')], verbose_name='成员角色 1群主 2管理员 3普通成员'),
        ),
    ]
