#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='mysql'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi

export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}"

python << END
import sys
import time
import pymysql

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        pymysql.connect(
            database="${MYSQL_DB}",
            user="${MYSQL_USER}",
            password="${MYSQL_PASSWORD}",
            host="${MYSQL_HOST}",
            port=${MYSQL_PORT},
        )
        break
    except pymysql.OperationalError as error:
        sys.stderr.write("正在等待MySQL可用...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  这花费的时间比预期的要长。以下异常可能表示不可恢复的错误： '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'MySQL is available'

exec "$@"
