#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


while ! nc -z db 3306 ; do
    echo "等待MySQL服务器"
    sleep 3
done
python /app/manage.py migrate
python /app/manage.py init_data
python /app/manage.py init_keyword
python /app/manage.py runserver 0.0.0.0:8000
