#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py init_data
python /app/manage.py init_keyword
python /app/manage.py runserver 0.0.0.0:8000
