@startmindmap
'https://plantuml.com/mindmap-diagram

* <&flag>Afan Chat
++ <&globe>连接管理
***_ Channels 实现 websocket_
***_ 消息推送
***_ 协议约定 json+type
***_ 心跳检测
++ <&people>用户模块
***_ 用户背包
****_ 徽章
****_ 改名卡
***_ 认证模块
****_ 微信扫码登录
****_ token认证
****_ token 过期
***_ 黑名单
***_ ip归属地
++ <&star>消息模块_
***_ 消息类型
****_ 文本
*****_ 系统消息
*****_ 撤回消息
*****_ 通知消息
*****_ 链接
****_ 文件
*****_ 语音
*****_ 图片
*****_ 表情
****_ 消息列表 游标翻页
****_ 消息回复 定位跳转
****_ 消息时间展示
****_ 消息推送
****_ 消息标记
*****_ 点赞
*****_ 点踩
****_ url 解析卡片 责任链模式
****_ 消息撤回
****_ @成员
****_ gpt上下文
****_ 敏感词检测
****_ 发送消息 策略模式
** 群成员模块
***_ 在线人数+总人数
***_ 群成员列表 游标翻页
***_ 上下线推送
left side
** 会话列表
***_ 加好友
***_ 群聊
***_ 单聊
***_ 已读未读
***_ 推拉结合
** 基础功能
***_ 接口日志打印
***_ ip异步解析
***_ 频控
***_ 分布式锁
***_ 异常处理
***_ 本地消息表
** 中间键
***_ redis
***_ mysql
***_ ngnix
***_ miniIO





'    * 登录
'** <&pulse>SolydXK
'** <&people>SteamOS
'** <&star>Raspbian with a very long name
'*** <s>Raspmbc</s> => OSMC
'*** <s>Raspyfi</s> => Volumio

left side


@endmindmap
